<script setup>
import { computed, onMounted, ref } from 'vue'
const coreUrl = new URL(window.location.href); coreUrl.port = String(window.TIMETIP_CONFIG?.corePort || 8787); coreUrl.pathname = '/'; const core = import.meta.env.VITE_CORE_URL || coreUrl.origin
const token = ref(localStorage.getItem('time_tip_token') || '')
const username = ref(''); const password = ref(''); const loginError = ref(''); const loading = ref(false)
const stats = ref({ total_downloads: 0, successful_downloads: 0, by_source: [], recent: [] })
const packages = ref([]); const syncMessage = ref(''); const uploadFile = ref(null); const uploadVersion = ref(''); const uploadProgress = ref(0); const uploading = ref(false)
const loggedIn = computed(() => Boolean(token.value))
async function api(path, options = {}) { const headers = { ...(options.headers || {}), ...(token.value ? { 'X-Auth-Token': token.value } : {}) }; const res = await fetch(core + path, { ...options, headers }); if (res.status === 401) { token.value = ''; localStorage.removeItem('time_tip_token'); throw new Error('登录已过期') }; return res }
async function login() { loginError.value = ''; loading.value = true; try { const res = await fetch(core + '/api/auth/login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({username: username.value, password: password.value}) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || '登录失败'); token.value = data.token; localStorage.setItem('time_tip_token', token.value); await loadAll() } catch (e) { loginError.value = e.message } finally { loading.value = false } }
async function loadAll() { const [s, p] = await Promise.all([api('/api/admin/stats'), api('/api/admin/packages')]); stats.value = await s.json(); packages.value = (await p.json()).items }
async function syncNow() { syncMessage.value = '正在同步…'; try { const data = await (await api('/api/admin/sync', {method:'POST'})).json(); syncMessage.value = data.message; await loadAll() } catch (e) { syncMessage.value = e.message } }
function chooseFile(e) { uploadFile.value = e.target.files[0] }
function uploadWithProgress(body) { return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', core + '/api/admin/upload'); if (token.value) xhr.setRequestHeader('X-Auth-Token', token.value); xhr.upload.onprogress = e => { if (e.lengthComputable) uploadProgress.value = Math.round(e.loaded / e.total * 100) }; xhr.onload = () => { let data = {}; try { data = JSON.parse(xhr.responseText) } catch {} if (xhr.status === 401) { token.value = ''; localStorage.removeItem('time_tip_token') } if (xhr.status >= 200 && xhr.status < 300) resolve(data); else reject(new Error(data.error || '上传失败')) }; xhr.onerror = () => reject(new Error('网络错误')); xhr.send(body) }) }
async function upload() { if (!uploadFile.value || uploading.value) return; const version = uploadVersion.value.trim(); if (!/^V\d+\.\d+\.\d+$/.test(version)) { syncMessage.value = '版本号必须为 VX.X.X，例如 V1.4.7'; return }; if (packages.value.some(p => p.version === version && p.filename === uploadFile.value.name.replace(/[^\w.()-]/g, '_'))) { syncMessage.value = '该安装包已上传，请勿重复上传'; return }; const body = new FormData(); body.append('file', uploadFile.value); body.append('version', version); uploading.value = true; uploadProgress.value = 0; syncMessage.value = '正在上传…'; try { await uploadWithProgress(body); syncMessage.value = '上传成功'; uploadFile.value = null; await loadAll() } catch (e) { syncMessage.value = e.message } finally { uploading.value = false } }
async function deletePackage(p) { if (!window.confirm(`确定删除 ${p.version} ${p.filename}？`)) return; try { await api(`/api/admin/packages/${p.id}`, {method:'DELETE'}); syncMessage.value = '已删除'; await loadAll() } catch (e) { syncMessage.value = e.message } }
async function setLatest(p) { try { await api(`/api/admin/packages/${p.id}/latest`, {method:'POST'}); syncMessage.value = `已指定 ${p.version} 为更新版本`; await loadAll() } catch (e) { syncMessage.value = e.message } }
function downloadUrl(p) { return `${core}/api/client/update/download/${p.id}` }
onMounted(() => { if (loggedIn.value) loadAll().catch(() => {}) })
</script>
<template>
  <main class="shell" v-if="!loggedIn"><section class="login card"><div class="brand">TIME-TIP</div><h1>后台服务管理</h1><p class="muted">登录后管理客户端版本和更新包</p><form @submit.prevent="login"><label>用户名<input v-model="username" autocomplete="username" required /></label><label>密码<input v-model="password" type="password" autocomplete="current-password" required /></label><button :disabled="loading">{{ loading ? '登录中…' : '登录' }}</button><p class="error">{{ loginError }}</p></form></section></main>
  <main class="app" v-else><header><div><div class="eyebrow">TIME-TIP SERVICE</div><h1>后台服务控制台</h1></div><button class="secondary" @click="loadAll">刷新数据</button></header><section class="cards"><div class="metric"><span>累计下载</span><strong>{{ stats.total_downloads }}</strong></div><div class="metric"><span>成功下载</span><strong>{{ stats.successful_downloads }}</strong></div><div class="metric"><span>GitHub 下载</span><strong>{{ (stats.by_source.find(x => x.source === 'github') || {}).downloads || 0 }}</strong></div><div class="metric"><span>手动上传下载</span><strong>{{ (stats.by_source.find(x => x.source === 'manual') || {}).downloads || 0 }}</strong></div></section><section class="grid"><div class="card"><div class="section-title"><h2>版本同步</h2><button @click="syncNow">立即同步 GitHub</button></div><p class="muted">每日自动检查 release 分支，也可以手动触发同步。</p><p class="notice">{{ syncMessage }}</p><div class="upload"><input type="file" accept=".exe" @change="chooseFile" :disabled="uploading"/><input v-model="uploadVersion" placeholder="版本号，例如 V1.4.7" :disabled="uploading"/><button class="secondary" @click="upload" :disabled="uploading">{{ uploading ? `上传中 ${uploadProgress}%` : '上传安装包' }}</button></div><div v-if="uploading" class="progress"><div class="progress-bar" :style="{width: uploadProgress + '%'}"></div></div></div><div class="card"><div class="section-title"><h2>安装包</h2><span class="pill">Windows x64</span></div><div class="table-wrap"><table><thead><tr><th>版本</th><th>来源</th><th>文件</th><th>时间</th><th>操作</th></tr></thead><tbody><tr v-for="p in packages" :key="p.id"><td>{{ p.version }} <span v-if="p.is_latest" class="pill latest">当前更新</span></td><td><span :class="['pill', p.source]">{{ p.source === 'github' ? 'GitHub' : '手动上传' }}</span></td><td>{{ p.filename }}</td><td>{{ new Date(p.created_at).toLocaleString() }}</td><td class="actions"><a :href="downloadUrl(p)">下载</a><button class="link-btn" @click="setLatest(p)" :disabled="p.is_latest">指定更新</button><button class="link-btn danger" @click="deletePackage(p)">删除</button></td></tr><tr v-if="!packages.length"><td colspan="5" class="muted">暂无安装包</td></tr></tbody></table></div></div></section><section class="card"><div class="section-title"><h2>最近下载记录</h2></div><div class="table-wrap"><table><thead><tr><th>版本</th><th>来源</th><th>客户端版本</th><th>IP</th><th>时间</th></tr></thead><tbody><tr v-for="r in stats.recent" :key="r.id"><td>{{ r.version }}</td><td>{{ r.source }}</td><td>{{ r.client_version || '-' }}</td><td>{{ r.client_ip }}</td><td>{{ new Date(r.created_at).toLocaleString() }}</td></tr><tr v-if="!stats.recent.length"><td colspan="5" class="muted">暂无记录</td></tr></tbody></table></div></section></main>
</template>
