<script setup>
import { computed, onMounted, ref } from 'vue'
const coreUrl = new URL(window.location.href); coreUrl.port = String(window.TIMETIP_CONFIG?.corePort || 8787); coreUrl.pathname = '/'; const core = import.meta.env.VITE_CORE_URL || coreUrl.origin
const token = ref(localStorage.getItem('time_tip_token') || '')
const username = ref(''); const password = ref(''); const loginError = ref(''); const loading = ref(false)
const stats = ref({ total_downloads: 0, successful_downloads: 0, by_source: [], recent: [] })
const packages = ref([]); const syncMessage = ref(''); const uploadFile = ref(null); const uploadVersion = ref('')
const loggedIn = computed(() => Boolean(token.value))
async function api(path, options = {}) { const headers = { ...(options.headers || {}), ...(token.value ? { 'X-Auth-Token': token.value } : {}) }; const res = await fetch(core + path, { ...options, headers }); if (res.status === 401) { token.value = ''; localStorage.removeItem('time_tip_token'); throw new Error('登录已过期') }; return res }
async function login() { loginError.value = ''; loading.value = true; try { const res = await fetch(core + '/api/auth/login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({username: username.value, password: password.value}) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || '登录失败'); token.value = data.token; localStorage.setItem('time_tip_token', token.value); await loadAll() } catch (e) { loginError.value = e.message } finally { loading.value = false } }
async function loadAll() { const [s, p] = await Promise.all([api('/api/admin/stats'), api('/api/admin/packages')]); stats.value = await s.json(); packages.value = (await p.json()).items }
async function syncNow() { syncMessage.value = '正在同步…'; try { const data = await (await api('/api/admin/sync', {method:'POST'})).json(); syncMessage.value = data.message; await loadAll() } catch (e) { syncMessage.value = e.message } }
function chooseFile(e) { uploadFile.value = e.target.files[0] }
async function upload() { if (!uploadFile.value) return; const body = new FormData(); body.append('file', uploadFile.value); body.append('version', uploadVersion.value || 'unknown'); const data = await (await api('/api/admin/upload', {method:'POST', body})).json(); syncMessage.value = data.ok ? '上传成功' : data.error; await loadAll() }
onMounted(() => { if (loggedIn.value) loadAll().catch(() => {}) })
</script>
<template>
  <main class="shell" v-if="!loggedIn"><section class="login card"><div class="brand">TIME-TIP</div><h1>后台服务管理</h1><p class="muted">登录后管理客户端版本和更新包</p><form @submit.prevent="login"><label>用户名<input v-model="username" autocomplete="username" required /></label><label>密码<input v-model="password" type="password" autocomplete="current-password" required /></label><button :disabled="loading">{{ loading ? '登录中…' : '登录' }}</button><p class="error">{{ loginError }}</p></form></section></main>
  <main class="app" v-else><header><div><div class="eyebrow">TIME-TIP SERVICE</div><h1>后台服务控制台</h1></div><button class="secondary" @click="loadAll">刷新数据</button></header><section class="cards"><div class="metric"><span>累计下载</span><strong>{{ stats.total_downloads }}</strong></div><div class="metric"><span>成功下载</span><strong>{{ stats.successful_downloads }}</strong></div><div class="metric"><span>GitHub 下载</span><strong>{{ (stats.by_source.find(x => x.source === 'github') || {}).downloads || 0 }}</strong></div><div class="metric"><span>手动上传下载</span><strong>{{ (stats.by_source.find(x => x.source === 'manual') || {}).downloads || 0 }}</strong></div></section><section class="grid"><div class="card"><div class="section-title"><h2>版本同步</h2><button @click="syncNow">立即同步 GitHub</button></div><p class="muted">每日自动检查 release 分支，也可以手动触发同步。</p><p class="notice">{{ syncMessage }}</p><div class="upload"><input type="file" accept=".exe" @change="chooseFile"/><input v-model="uploadVersion" placeholder="版本号，例如 1.4.7"/><button class="secondary" @click="upload">上传安装包</button></div></div><div class="card"><div class="section-title"><h2>安装包</h2><span class="pill">Windows x64</span></div><div class="table-wrap"><table><thead><tr><th>版本</th><th>来源</th><th>文件</th><th>时间</th></tr></thead><tbody><tr v-for="p in packages" :key="p.id"><td>{{ p.version }}</td><td><span :class="['pill', p.source]">{{ p.source === 'github' ? 'GitHub' : '手动上传' }}</span></td><td>{{ p.filename }}</td><td>{{ new Date(p.created_at).toLocaleString() }}</td></tr><tr v-if="!packages.length"><td colspan="4" class="muted">暂无安装包</td></tr></tbody></table></div></div></section><section class="card"><div class="section-title"><h2>最近下载记录</h2></div><div class="table-wrap"><table><thead><tr><th>版本</th><th>来源</th><th>客户端版本</th><th>IP</th><th>时间</th></tr></thead><tbody><tr v-for="r in stats.recent" :key="r.id"><td>{{ r.version }}</td><td>{{ r.source }}</td><td>{{ r.client_version || '-' }}</td><td>{{ r.client_ip }}</td><td>{{ new Date(r.created_at).toLocaleString() }}</td></tr><tr v-if="!stats.recent.length"><td colspan="5" class="muted">暂无记录</td></tr></tbody></table></div></section></main>
</template>
